CREATE TABLE [dbo].[PRODUCTDEPLOYPLAN]
(
	[PRODUCTID] INT NOT NULL , 
    [PRODUCTNAME] NVARCHAR(50) NOT NULL, 
    [PRODUCTWIDTH] NUMERIC(18, 4) NOT NULL, 
    [DEFAULTPOSITION] SMALLINT NOT NULL, 
    [SHELFWIDTH] NUMERIC(18, 4) NOT NULL,
	CONSTRAINT [PK_PRODUCTDEPLOYPLAN] PRIMARY KEY CLUSTERED([PRODUCTID] ASC)
)
GO